# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8edf6f778bc78278a7253cf1369b35a68ef2001806f06c2369fe98b4e1cb8ff3e2dd3ed75b719b6669881322ce4ae16a3b0760a3cbbeb8ae1844815c6b6d3d9c

test:
  secret_key_base: 29bb0d34d4395829c7fda607f73e9cbd1b13d9c3cb689ee489d91e5967df2cb14772492c8f06cf1abe4a2dceb5e2c0873426fafc9291eef2b6df66289e962f99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
